#
# Specific settings for local test driven development
#
settings:
  # Sets event.requestContext.stage to this value
  stage: 'dev'

  # These values are not used when running on a development computer but prevent Serverless errors
  apiHostName: 'api.authsamples.com'
  certificateDomainName: 'authsamples.com'
